import { useEffect, useRef, useState } from 'react';
import katex from 'katex';
import ClusteringTableOfContents from './components/ClusteringTableOfContents';
import './styles/global.css';

const BLUE='#245cff',ORANGE='#e67e22',GREEN='#22995f',RED='#d84a4a',PURPLE='#7654d8',GRID='rgba(16, 19, 24, 0.14)',COLORS=[BLUE,RED,GREEN,PURPLE,ORANGE,'#1596a3'];
function K({l,block=false}){const ref=useRef(null);useEffect(()=>{if(ref.current)katex.render(l,ref.current,{throwOnError:false,displayMode:block});},[l,block]);return block?<div ref={ref} style={{overflowX:'auto',margin:'.8rem 0'}}/>:<span ref={ref}/>;}
function Navbar(){const[menuOpen,setMenuOpen]=useState(false);return <nav className="ns-nav"><a className="nav-mark" href="/"><span className="dot"/></a><button className="ns-nav-burger" aria-label="Toggle menu" onClick={()=>setMenuOpen(o=>!o)}>☰</button><div className={`ns-nav-links${menuOpen?' mobile-open':''}`}>{['about','research','experience','education','studyguides','beyond'].map(item=><a key={item} href={`/#${item}`}>{item==='studyguides'?'study guides':item}</a>)}<a href="/" target="_blank" rel="noopener">cv</a><span className="nav-pipe">|</span><a href="https://kimchikorelileriniskembesidir.com" className="field-notes" target="_blank" rel="noopener">personal blog</a></div></nav>;}
function Artifact({title,children}){return <div className="artifact-card"><h4>{title}</h4>{children}</div>;}
function Control({label,value,children}){return <label style={{display:'grid',gap:'.35rem',minWidth:145,flex:1}}><span style={{display:'flex',justifyContent:'space-between',gap:'1rem',color:'var(--muted)',fontFamily:'var(--ff-mono)',fontSize:'.72rem'}}><span>{label}</span><strong style={{color:BLUE}}>{value}</strong></span>{children}</label>;}
function Metric({label,value,color=BLUE,note}){return <div style={{background:'#fff',padding:'.85rem 1rem',minWidth:0}}><div style={{color:'var(--muted)',fontFamily:'var(--ff-mono)',fontSize:'.66rem'}}>{label}</div><div style={{color,fontSize:'1.2rem',fontWeight:700}}>{value}</div>{note&&<div style={{color:'var(--muted)',fontSize:'.74rem'}}>{note}</div>}</div>;}
function MetricGrid({children}){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(125px, 1fr))',gap:1,background:GRID,border:`1px solid ${GRID}`,marginTop:'1rem'}}>{children}</div>;}
function ChoiceButtons({choices,value,onChange}){return <div style={{display:'flex',gap:'.5rem',flexWrap:'wrap',marginBottom:'1rem'}}>{choices.map(([id,label])=><button key={id} type="button" aria-pressed={value===id} onClick={()=>onChange(id)} style={{padding:'.45rem .75rem',border:`1px solid ${value===id?BLUE:GRID}`,background:value===id?'#eef2ff':'#fff',color:value===id?BLUE:'var(--muted)',cursor:'pointer'}}>{label}</button>)}</div>;}

const DATA=[[.6,1],[.9,1.5],[1.2,.8],[1.5,1.4],[1.7,.7],[2,1.2],[2.5,3.8],[2.8,4.4],[3.1,3.6],[3.3,4.1],[3.6,4.6],[3.9,3.8],[4.3,1.3],[4.6,1.8],[4.8,.9],[5.1,1.5],[5.4,.8],[5.6,1.7]];
const sx=x=>44+x/6.2*566,sy=y=>225-y/5.3*190,dist2=(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2;
function initialCentroids(k,mode){if(mode==='poor')return DATA.slice(0,k).map(p=>[...p]);const ordered=[0,12,7,4,16,10];return Array.from({length:k},(_,i)=>[...DATA[ordered[i%ordered.length]]]);}
function runKMeans(k,iterations,mode='spread'){let centroids=initialCentroids(k,mode),assignments=[];for(let step=0;step<=iterations;step+=1){assignments=DATA.map(p=>centroids.reduce((best,c,index)=>dist2(p,c)<best.d?{index,d:dist2(p,c)}:best,{index:0,d:Infinity}).index);if(step===iterations)break;centroids=centroids.map((c,index)=>{const members=DATA.filter((_,i)=>assignments[i]===index);return members.length?[members.reduce((s,p)=>s+p[0],0)/members.length,members.reduce((s,p)=>s+p[1],0)/members.length]:c;});}const sse=DATA.reduce((sum,p,i)=>sum+dist2(p,centroids[assignments[i]]),0);return{centroids,assignments,sse};}

function KMeansExplorer(){const[k,setK]=useState(3),[iterations,setIterations]=useState(2),[mode,setMode]=useState('spread');const result=runKMeans(k,iterations,mode);return <Artifact title="Interactive · Alternate assignment and update"><ChoiceButtons choices={[["spread","Spread seeds"],["poor","Crowded seeds"]]} value={mode} onChange={setMode}/><div style={{display:'flex',gap:'1.3rem',flexWrap:'wrap'}}><Control label="clusters k" value={k}><input aria-label="K-means cluster count" type="range" min="2" max="5" value={k} onChange={e=>setK(Number(e.target.value))}/></Control><Control label="update rounds" value={iterations}><input aria-label="K-means update rounds" type="range" min="0" max="8" value={iterations} onChange={e=>setIterations(Number(e.target.value))}/></Control></div><svg viewBox="0 0 640 260" role="img" aria-label="K-means points, assignments, and centroids" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}>{[1,2,3,4,5].map(v=><g key={v}><line x1={sx(v)} y1="35" x2={sx(v)} y2="225" stroke={GRID}/><line x1="44" y1={sy(v)} x2="610" y2={sy(v)} stroke={GRID}/></g>)}{DATA.map((p,i)=><circle key={i} cx={sx(p[0])} cy={sy(p[1])} r="6" fill={COLORS[result.assignments[i]]}/>) }{result.centroids.map((c,i)=><g key={i}><line x1={sx(c[0])-9} y1={sy(c[1])-9} x2={sx(c[0])+9} y2={sy(c[1])+9} stroke="#101318" strokeWidth="4"/><line x1={sx(c[0])+9} y1={sy(c[1])-9} x2={sx(c[0])-9} y2={sy(c[1])+9} stroke="#101318" strokeWidth="4"/></g>)}</svg><MetricGrid><Metric label="within-cluster SSE" value={result.sse.toFixed(2)} color={result.sse<8?GREEN:RED}/><Metric label="iterations" value={iterations} color={PURPLE}/><Metric label="initialization" value={mode==='spread'?'diverse':'crowded'} color={mode==='spread'?GREEN:ORANGE}/></MetricGrid></Artifact>;}

function ElbowExplorer(){const[selectedK,setSelectedK]=useState(3);const results=Array.from({length:6},(_,i)=>runKMeans(i+1,8,'spread'));const max=results[0].sse;const path=results.map((r,i)=>`${i?'L':'M'} ${65+i/5*525} ${220-r.sse/max*175}`).join(' ');const current=results[selectedK-1];return <Artifact title="Interactive · Elbow and partition size"><Control label="candidate k" value={selectedK}><input aria-label="Elbow candidate clusters" type="range" min="1" max="6" value={selectedK} onChange={e=>setSelectedK(Number(e.target.value))}/></Control><svg viewBox="0 0 640 250" role="img" aria-label="K-means SSE elbow curve" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}>{[1,2,3,4,5,6].map((v,i)=><g key={v}><line x1={65+i/5*525} y1="40" x2={65+i/5*525} y2="220" stroke={GRID}/><text x={65+i/5*525} y="241" textAnchor="middle" fontFamily="monospace" fontSize="10">{v}</text></g>)}<path d={path} fill="none" stroke={BLUE} strokeWidth="3"/>{results.map((r,i)=><circle key={i} cx={65+i/5*525} cy={220-r.sse/max*175} r={i===selectedK-1?8:5} fill={i===selectedK-1?ORANGE:GREEN}/>)}</svg><MetricGrid><Metric label="SSE at selected k" value={current.sse.toFixed(2)} color={BLUE}/><Metric label="clusters" value={selectedK} color={PURPLE}/><Metric label="next question" value={selectedK===3?'natural elbow':'inspect stability'} color={selectedK===3?GREEN:ORANGE}/></MetricGrid><p style={{color:'var(--muted)',fontSize:'.82rem',marginBottom:0}}>SSE always decreases as <K l="k"/> grows. Look for diminishing returns, then confirm with silhouette, stability, and domain usefulness.</p></Artifact>;}

function SilhouetteExplorer(){const[position,setPosition]=useState(30);const x=position/10,own=[[1,1],[1.3,1.5],[1.7,.9]],other=[[4.1,3.7],[4.5,4.2],[4.9,3.5]];const point=[x,1.4];const avg=arr=>arr.reduce((s,p)=>s+Math.sqrt(dist2(point,p)),0)/arr.length;const a=avg(own),b=avg(other),score=(b-a)/Math.max(a,b);return <Artifact title="Interactive · Cohesion versus separation"><Control label="move one assigned point" value={`x=${x.toFixed(1)}`}><input aria-label="Silhouette point position" type="range" min="5" max="50" value={position} onChange={e=>setPosition(Number(e.target.value))}/></Control><svg viewBox="0 0 640 240" role="img" aria-label="Point distances used for silhouette coefficient" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}>{own.map((p,i)=><circle key={`a${i}`} cx={sx(p[0])} cy={sy(p[1])} r="6" fill={BLUE}/>)}{other.map((p,i)=><circle key={`b${i}`} cx={sx(p[0])} cy={sy(p[1])} r="6" fill={GREEN}/>)}{[...own,...other].map((p,i)=><line key={i} x1={sx(point[0])} y1={sy(point[1])} x2={sx(p[0])} y2={sy(p[1])} stroke={i<own.length?BLUE:ORANGE} opacity=".45"/>)}<circle cx={sx(point[0])} cy={sy(point[1])} r="9" fill={score>=0?PURPLE:RED} stroke="#fff" strokeWidth="3"/></svg><K block l="s(i)=\frac{b(i)-a(i)}{\max\{a(i),b(i)\}}"/><MetricGrid><Metric label="cohesion distance a(i)" value={a.toFixed(2)} color={BLUE}/><Metric label="nearest-cluster distance b(i)" value={b.toFixed(2)} color={GREEN}/><Metric label="silhouette s(i)" value={score.toFixed(2)} color={score>.5?GREEN:score>=0?ORANGE:RED}/></MetricGrid></Artifact>;}

const MOONS=[...Array.from({length:14},(_,i)=>{const a=Math.PI*i/13;return[1.8+1.3*Math.cos(a),2.1+1.3*Math.sin(a),0];}),...Array.from({length:14},(_,i)=>{const a=Math.PI*i/13;return[3.3-1.3*Math.cos(a),1.9-1.3*Math.sin(a),1];})];
function ShapeExplorer(){const[method,setMethod]=useState('kmeans');return <Artifact title="Interactive · Centroids cannot wrap around moons"><ChoiceButtons choices={[["truth","Natural shape"],["kmeans","K-means cut"],["kernel","Nonlinear feature view"]]} value={method} onChange={setMethod}/><svg viewBox="0 0 640 250" role="img" aria-label="Non-globular clusters and K-means limitation" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`}}>{MOONS.map((p,i)=>{const color=method==='truth'?COLORS[p[2]]:method==='kmeans'?(p[1]>1.9?BLUE:RED):(p[2]?GREEN:PURPLE);return <circle key={i} cx={sx(p[0])} cy={sy(p[1])} r="6" fill={color}/>})}{method==='kmeans'&&<line x1="44" y1={sy(1.9)} x2="610" y2={sy(1.9)} stroke={ORANGE} strokeWidth="3"/>}</svg><p style={{color:'var(--muted)',fontSize:'.82rem',marginBottom:0}}>{method==='kmeans'?'Nearest-centroid Voronoi regions are convex, so a straight cut splits both curved manifolds.':method==='kernel'?'A nonlinear representation can make the two shapes separable before clustering.':'The intended clusters follow connected curved shapes, not spherical clouds.'}</p></Artifact>;}

const CLUSTER_A=[[1,1],[1.3,1.7],[1.8,1.2]],CLUSTER_B=[[3.7,3.5],[4.2,4.1],[5,3.2]];
function LinkageExplorer(){const[linkage,setLinkage]=useState('single');const pairs=CLUSTER_A.flatMap(a=>CLUSTER_B.map(b=>Math.sqrt(dist2(a,b))));const values={single:Math.min(...pairs),complete:Math.max(...pairs),average:pairs.reduce((a,b)=>a+b,0)/pairs.length,ward:(CLUSTER_A.length*CLUSTER_B.length/(CLUSTER_A.length+CLUSTER_B.length))*dist2([CLUSTER_A.reduce((s,p)=>s+p[0],0)/3,CLUSTER_A.reduce((s,p)=>s+p[1],0)/3],[CLUSTER_B.reduce((s,p)=>s+p[0],0)/3,CLUSTER_B.reduce((s,p)=>s+p[1],0)/3])};return <Artifact title="Interactive · Linkage changes what 'closest' means"><ChoiceButtons choices={[["single","Single / MIN"],["complete","Complete / MAX"],["average","Group average"],["ward","Ward"]]} value={linkage} onChange={setLinkage}/><svg viewBox="0 0 640 245" role="img" aria-label="Two clusters under different linkage definitions" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`}}>{CLUSTER_A.map((p,i)=><circle key={`a${i}`} cx={sx(p[0])} cy={sy(p[1])} r="7" fill={BLUE}/>)}{CLUSTER_B.map((p,i)=><circle key={`b${i}`} cx={sx(p[0])} cy={sy(p[1])} r="7" fill={GREEN}/>)}{linkage==='average'&&CLUSTER_A.flatMap((a,i)=>CLUSTER_B.map((b,j)=><line key={`${i}-${j}`} x1={sx(a[0])} y1={sy(a[1])} x2={sx(b[0])} y2={sy(b[1])} stroke={ORANGE} opacity=".2"/>))}{linkage==='single'&&<line x1={sx(1.8)} y1={sy(1.2)} x2={sx(3.7)} y2={sy(3.5)} stroke={ORANGE} strokeWidth="3"/>}{linkage==='complete'&&<line x1={sx(1)} y1={sy(1)} x2={sx(5)} y2={sy(3.2)} stroke={RED} strokeWidth="3"/>}</svg><MetricGrid><Metric label={`${linkage} linkage`} value={values[linkage].toFixed(2)} color={linkage==='complete'?RED:PURPLE}/><Metric label="structural bias" value={linkage==='single'?'chaining':linkage==='complete'?'compact':linkage==='average'?'balanced':'low SSE'} color={ORANGE}/></MetricGrid></Artifact>;}

function DendrogramExplorer(){const[cut,setCut]=useState(55);const height=cut/100;const clusters=height<.25?6:height<.48?4:height<.72?2:1;return <Artifact title="Interactive · Cut a dendrogram at a chosen scale"><Control label="cut height D*" value={height.toFixed(2)}><input aria-label="Dendrogram cut height" type="range" min="10" max="90" value={cut} onChange={e=>setCut(Number(e.target.value))}/></Control><svg viewBox="0 0 640 260" role="img" aria-label="Hierarchical clustering dendrogram and cut" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}><path d="M90 220V180H150V220 M120 180V130H230V220 M200 220V165H260V220 M215 130V90H415V220 M380 220V150H450V220 M415 150V115H520V220 M485 220V175H550V220" fill="none" stroke="#101318" strokeWidth="2"/><line x1="50" y1={220-height*180} x2="590" y2={220-height*180} stroke={RED} strokeWidth="3" strokeDasharray="6 5"/>{[90,150,200,260,380,450,485,550].map((x,i)=><text key={i} x={x} y="242" textAnchor="middle" fontFamily="monospace" fontSize="10">p{i+1}</text>)}</svg><MetricGrid><Metric label="clusters below cut" value={clusters} color={PURPLE}/><Metric label="cut height" value={height.toFixed(2)} color={RED}/><Metric label="interpretation" value={clusters===1?'one coarse group':clusters>=5?'fine partition':'nested groups'} color={GREEN}/></MetricGrid></Artifact>;}

const DENSITY_POINTS=[[.7,1],[1,1.2],[1.2,.8],[1.4,1.3],[1.6,1],[2,1.5],[2.4,2],[2.8,2.4],[3.2,2.8],[3.6,3.2],[4,3.7],[4.3,3.5],[4.6,4],[4.9,3.6],[5.2,4.1],[5.6,.7],[.5,4.5]];
function DbscanExplorer(){const[epsValue,setEpsValue]=useState(8),[minPts,setMinPts]=useState(3);const eps=epsValue/10;const neighbors=DENSITY_POINTS.map((p)=>DENSITY_POINTS.filter(q=>Math.sqrt(dist2(p,q))<=eps).length);const core=neighbors.map(n=>n>=minPts);const type=DENSITY_POINTS.map((p,i)=>core[i]?'core':DENSITY_POINTS.some((q,j)=>core[j]&&Math.sqrt(dist2(p,q))<=eps)?'border':'noise');const counts=t=>type.filter(v=>v===t).length;return <Artifact title="Interactive · DBSCAN core, border, and noise"><div style={{display:'flex',gap:'1.3rem',flexWrap:'wrap'}}><Control label="radius ε" value={eps.toFixed(1)}><input aria-label="DBSCAN epsilon" type="range" min="3" max="18" value={epsValue} onChange={e=>setEpsValue(Number(e.target.value))}/></Control><Control label="minimum points" value={minPts}><input aria-label="DBSCAN minimum points" type="range" min="2" max="7" value={minPts} onChange={e=>setMinPts(Number(e.target.value))}/></Control></div><svg viewBox="0 0 640 260" role="img" aria-label="DBSCAN point types under epsilon and minimum points" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}>{DENSITY_POINTS.map((p,i)=><g key={i}>{type[i]==='core'&&<circle cx={sx(p[0])} cy={sy(p[1])} r={eps/6.2*566} fill="none" stroke={GREEN} opacity=".12"/>}<circle cx={sx(p[0])} cy={sy(p[1])} r={type[i]==='core'?7:6} fill={type[i]==='core'?GREEN:type[i]==='border'?ORANGE:RED}/></g>)}</svg><MetricGrid><Metric label="core points" value={counts('core')} color={GREEN}/><Metric label="border points" value={counts('border')} color={ORANGE}/><Metric label="noise points" value={counts('noise')} color={RED}/></MetricGrid></Artifact>;}

export default function ClusteringApp(){return <div style={{background:'var(--bg)',minHeight:'100vh'}}><Navbar/><header className="ns-header"><div className="container"><div style={{fontSize:'.82rem',color:'var(--muted)',marginBottom:'.35rem'}}><a href="/machinelearning/">Machine Learning</a> ›</div><div className="ns-title">Clustering</div><div className="ns-subtitle">Discover structure without labels through centroid partitions, nested hierarchies, and density-connected regions—while making the geometry and validation assumptions explicit.</div><span className="tag">K-means · hierarchical linkage · density clustering</span></div></header><div className="container"><div className="ns-layout"><aside className="ns-sidebar"><ClusteringTableOfContents/></aside><main className="ns-content">
<section id="setup" className="ns-section"><h2>1. The Clustering Problem</h2><p>Clustering partitions observations using only their features. Unlike supervised learning, there is no target label to define the correct grouping.</p><K block l="\mathcal D=\{x_1,\ldots,x_N\},\qquad z_i\in\{1,\ldots,K\}"/><p>Applications include organizing documents and search results, compressing images, identifying patient subtypes, exploratory biology, and segmenting behavior. A cluster is meaningful only relative to a representation, distance, scale, and intended use.</p><table><thead><tr><th>Family</th><th>Definition of structure</th></tr></thead><tbody><tr><td>Partitional</td><td>Optimize one flat assignment, e.g. k-means</td></tr><tr><td>Hierarchical</td><td>Build nested merges or splits</td></tr><tr><td>Density-based</td><td>Connect dense regions separated by sparse space</td></tr></tbody></table></section>
<section id="kmeans" className="ns-section"><h2>2. K-Means Coordinate Descent</h2><K block l="J(z,\mu)=\sum_{i=1}^{N}\lVert x_i-\mu_{z_i}\rVert_2^2"/><ol><li>Assign every point to its nearest centroid: <K l="z_i\leftarrow\arg\min_k\lVert x_i-\mu_k\rVert^2"/>.</li><li>Replace each centroid by the mean of its assigned points: <K l="\mu_k\leftarrow |C_k|^{-1}\sum_{i:z_i=k}x_i"/>.</li><li>Repeat until assignments or objective stop changing.</li></ol><KMeansExplorer/><p>Each step cannot increase SSE, so the algorithm converges—but only to a local optimum.</p></section>
<section id="initialization" className="ns-section"><h2>3. Initialization Matters</h2><p>Poorly placed initial centroids can share one natural group, leave another uncovered, and converge to an inferior local minimum. Multiple random restarts retain the run with lowest objective.</p><K block l="P(\mu_{new}=x_i)\propto D(x_i)^2"/><p>K-means++ selects the first center randomly, then favors observations far from existing centers. The squared-distance lottery spreads seeds while retaining randomness. It generally improves both convergence speed and solution quality.</p><div className="formula-card"><strong>Empty cluster:</strong> if a centroid receives no points, reinitialize it to a far-away observation or split a high-variance cluster; do not silently divide by zero.</div></section>
<section id="choose-k" className="ns-section"><h2>4. Choosing the Number of Clusters</h2><ElbowExplorer/><SilhouetteExplorer/><p>Average silhouette near 1 indicates compact, separated groups; near 0 indicates overlap; negative values flag points that may be closer to another cluster. Internal scores are diagnostics, not proof of scientific truth.</p></section>
<section id="limits" className="ns-section"><h2>5. Where K-Means Fails</h2><p>Nearest-centroid assignments form convex Voronoi cells and implicitly favor similarly sized, similarly dense, spherical clusters. Unequal covariance, disparate size, outliers, and non-globular manifolds violate those assumptions.</p><ShapeExplorer/><ul><li>Standardize features when scale should not define importance.</li><li>Use robust distances or medoids when outliers make means unstable.</li><li>Use Gaussian mixtures for elliptical, probabilistic membership.</li><li>Use kernels, spectral methods, or density clustering for nonlinear shapes.</li></ul></section>
<section id="kernel" className="ns-section"><h2>6. Kernel K-Means</h2><p>Replace Euclidean distance by distance in an implicit feature space:</p><K block l="\lVert\phi(x)-\phi(\mu_k)\rVert^2=k(x,x)+k(\mu_k,\mu_k)-2k(x,\mu_k)"/><p>The feature-space mean is <K l="|C_k|^{-1}\sum_{i\in C_k}\phi(x_i)"/>, not generally <K l="\phi(\frac1{|C_k|}\sum x_i)"/>. Kernels enable nonlinear partitions such as concentric rings, but require a kernel choice and a potentially expensive similarity matrix.</p></section>
<section id="hierarchical" className="ns-section"><h2>7. Hierarchical Clustering</h2><p>Agglomerative clustering starts with each observation alone and repeatedly merges the closest two clusters. Divisive clustering starts with one group and recursively splits it.</p><ol><li>Compute a pairwise distance matrix.</li><li>Merge the closest active clusters.</li><li>Update distances using the chosen linkage.</li><li>Record each merge height in a dendrogram.</li><li>Cut the tree at a useful scale.</li></ol><p>No initial <K l="K"/> is required, and the hierarchy can represent taxonomies. Early greedy merges cannot be undone, and the full distance matrix can be expensive.</p></section>
<section id="linkage" className="ns-section"><h2>8. Linkage &amp; Dendrogram Cuts</h2><LinkageExplorer/><table><thead><tr><th>Linkage</th><th>Behavior</th></tr></thead><tbody><tr><td>Single / MIN</td><td>Follows chains and non-globular shapes; sensitive to bridges</td></tr><tr><td>Complete / MAX</td><td>Compact clusters; sensitive to extreme pair distances</td></tr><tr><td>Group average</td><td>Compromise using all cross-cluster pairs</td></tr><tr><td>Ward</td><td>Minimizes SSE increase; favors globular groups</td></tr></tbody></table><DendrogramExplorer/></section>
<section id="dbscan" className="ns-section"><h2>9. DBSCAN Density Connectivity</h2><p>DBSCAN defines density through an <K l="\varepsilon"/> neighborhood and a minimum point count. Core points have enough neighbors, border points neighbor a core, and remaining points are noise.</p><DbscanExplorer/><ol><li>Label core, border, and noise candidates.</li><li>Connect core points within <K l="\varepsilon"/>.</li><li>Each connected core component becomes a cluster.</li><li>Attach border points to a neighboring component; leave noise unassigned.</li></ol><p>DBSCAN finds arbitrary shapes and rejects noise without specifying <K l="K"/>, but one global density scale struggles when clusters have strongly different densities.</p></section>
<section id="practice" className="ns-section"><h2>10. Choosing &amp; Validating a Method</h2><table><thead><tr><th>Structure</th><th>Starting point</th></tr></thead><tbody><tr><td>Large, compact, similar-scale groups</td><td>K-means / mini-batch k-means</td></tr><tr><td>Nested taxonomy or unknown scale</td><td>Hierarchical clustering</td></tr><tr><td>Arbitrary shapes with explicit noise</td><td>DBSCAN</td></tr><tr><td>Elliptical overlapping membership</td><td>Gaussian mixture</td></tr><tr><td>Nonlinear graph/manifold structure</td><td>Kernel or spectral clustering</td></tr></tbody></table><h3>Validation checklist</h3><ul><li>Compare solutions across seeds, samples, scaling choices, and nearby hyperparameters.</li><li>Inspect cohesion, separation, silhouette, and cluster sizes.</li><li>Visualize in original features as well as projections.</li><li>Check whether groups predict external variables not used to form them.</li><li>Name clusters after examining data; do not treat algorithmic IDs as discovered identities.</li></ul></section>
<section id="references" className="ns-section"><h2>References &amp; Resources</h2><p>Lecture notes: CS512 Machine Learning, Assoc. Prof. Öznur Taştan (Sabancı University)</p></section>
</main></div></div><footer className="footer"><div className="footer-bg" aria-hidden="true"/><div className="footer-inner"><div className="footer-left"><p className="footer-email">adleyba [at] sabanciuniv [dot] edu</p><p style={{margin:'.5rem 0 0',fontSize:'.78rem',opacity:.6,fontFamily:'var(--ff-mono)'}}>Machine Learning Study Guide · Built with React + KaTeX</p></div><p className="footer-copy">© 2026 — SIMA ADLEYBA</p></div></footer></div>;}
