import { useEffect, useRef, useState } from 'react';
import katex from 'katex';
import PcaTableOfContents from './components/PcaTableOfContents';
import './styles/global.css';

const BLUE='#245cff',ORANGE='#e67e22',GREEN='#22995f',RED='#d84a4a',PURPLE='#7654d8',GRID='rgba(16, 19, 24, 0.14)';
function K({l,block=false}){const ref=useRef(null);useEffect(()=>{if(ref.current)katex.render(l,ref.current,{throwOnError:false,displayMode:block});},[l,block]);return block?<div ref={ref} style={{overflowX:'auto',margin:'.8rem 0'}}/>:<span ref={ref}/>;}
function Navbar(){const[o,setO]=useState(false);return <nav className="ns-nav"><a className="nav-mark" href="/"><span className="dot"/></a><button className="ns-nav-burger" aria-label="Toggle menu" onClick={()=>setO(v=>!v)}>☰</button><div className={`ns-nav-links${o?' mobile-open':''}`}>{['about','research','experience','education','studyguides','beyond'].map(i=><a key={i} href={`/#${i}`} onClick={()=>setO(false)}>{i==='studyguides'?'study guides':i}</a>)}<a href="/" target="_blank" rel="noopener">cv</a><span className="nav-pipe">|</span><a href="https://kimchikorelileriniskembesidir.com" className="field-notes" target="_blank" rel="noopener">personal blog</a></div></nav>;}
function Artifact({title,children}){return <div className="artifact-card"><h4>{title}</h4>{children}</div>;}
function Control({label,value,children}){return <label style={{display:'grid',gap:'.35rem',minWidth:145,flex:1}}><span style={{display:'flex',justifyContent:'space-between',gap:'1rem',color:'var(--muted)',fontFamily:'var(--ff-mono)',fontSize:'.72rem'}}><span>{label}</span><strong style={{color:BLUE}}>{value}</strong></span>{children}</label>;}
function Metric({label,value,color=BLUE,note}){return <div style={{background:'#fff',padding:'.85rem 1rem',minWidth:0}}><div style={{color:'var(--muted)',fontFamily:'var(--ff-mono)',fontSize:'.66rem'}}>{label}</div><div style={{color,fontSize:'1.2rem',fontWeight:700}}>{value}</div>{note&&<div style={{color:'var(--muted)',fontSize:'.74rem'}}>{note}</div>}</div>;}
function MetricGrid({children}){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(125px,1fr))',gap:1,background:GRID,border:`1px solid ${GRID}`,marginTop:'1rem'}}>{children}</div>;}
function Choices({choices,value,onChange}){return <div style={{display:'flex',gap:'.5rem',flexWrap:'wrap',marginBottom:'1rem'}}>{choices.map(([id,label])=><button key={id} type="button" aria-pressed={value===id} onClick={()=>onChange(id)} style={{padding:'.45rem .75rem',border:`1px solid ${value===id?BLUE:GRID}`,background:value===id?'#eef2ff':'#fff',color:value===id?BLUE:'var(--muted)',cursor:'pointer'}}>{label}</button>)}</div>;}

const POINTS=Array.from({length:24},(_,i)=>{const t=(i*2.399963)% (Math.PI*2),r=.25+((i*7)%17)/17;const u=2.25*r*Math.cos(t),v=.62*r*Math.sin(t),a=.55;return [u*Math.cos(a)-v*Math.sin(a),u*Math.sin(a)+v*Math.cos(a)];});
const sx=x=>320+x*105,sy=y=>130-y*72;
function CompressionExplorer(){const[d,setD]=useState(40),[k,setK]=useState(8);const safeK=Math.min(k,d),ratio=safeK/d;return <Artifact title="Interactive · Compress D coordinates into K scores"><div style={{display:'flex',gap:'1.3rem',flexWrap:'wrap'}}><Control label="original dimensions D" value={d}><input aria-label="PCA original dimensions" type="range" min="10" max="100" value={d} onChange={e=>{const next=Number(e.target.value);setD(next);setK(v=>Math.min(v,next));}}/></Control><Control label="retained components K" value={safeK}><input aria-label="PCA retained dimensions" type="range" min="1" max={d} value={safeK} onChange={e=>setK(Number(e.target.value))}/></Control></div><div style={{display:'grid',gridTemplateColumns:'1fr auto 1fr',alignItems:'center',gap:'1rem',marginTop:'1.3rem'}}><div style={{display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:3}}>{Array.from({length:Math.min(d,100)},(_,i)=><span key={i} style={{height:8,background:i<safeK?BLUE:'#d8dce4'}}/>)}</div><strong style={{color:ORANGE}}>Wᵀ</strong><div style={{display:'grid',gridTemplateColumns:'repeat(10,1fr)',gap:3}}>{Array.from({length:safeK},(_,i)=><span key={i} style={{height:8,background:PURPLE}}/>)}</div></div><K block l="z=W^T(x-\mu),\qquad \hat{x}=Wz+\mu"/><MetricGrid><Metric label="coordinate reduction" value={`${(100*(1-ratio)).toFixed(0)}%`} color={GREEN}/><Metric label="basis size" value={`${d} × ${safeK}`} color={PURPLE}/><Metric label="orthogonal directions" value={safeK} color={BLUE}/></MetricGrid></Artifact>;}

function ProjectionExplorer(){const[angle,setAngle]=useState(32),theta=angle*Math.PI/180,w=[Math.cos(theta),Math.sin(theta)];const projected=POINTS.map(p=>{const z=p[0]*w[0]+p[1]*w[1];return {p,q:[z*w[0],z*w[1]],z};}),variance=projected.reduce((s,p)=>s+p.z*p.z,0)/projected.length,mse=projected.reduce((s,{p,q})=>s+(p[0]-q[0])**2+(p[1]-q[1])**2,0)/projected.length;return <Artifact title="Interactive · Rotate the projection axis"><Control label="axis angle" value={`${angle}°`}><input aria-label="PCA projection angle" type="range" min="0" max="180" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></Control><svg viewBox="0 0 640 260" role="img" aria-label="Data points projected onto a rotating PCA axis" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem'}}><line x1={sx(-3*w[0])} y1={sy(-3*w[1])} x2={sx(3*w[0])} y2={sy(3*w[1])} stroke={BLUE} strokeWidth="3"/>{projected.map(({p,q},i)=><g key={i}><line x1={sx(p[0])} y1={sy(p[1])} x2={sx(q[0])} y2={sy(q[1])} stroke={ORANGE} opacity=".35"/><circle cx={sx(p[0])} cy={sy(p[1])} r="5" fill={PURPLE}/><circle cx={sx(q[0])} cy={sy(q[1])} r="2.5" fill={BLUE}/></g>)}</svg><MetricGrid><Metric label="projected variance" value={variance.toFixed(3)} color={GREEN}/><Metric label="reconstruction MSE" value={mse.toFixed(3)} color={ORANGE}/><Metric label="objective" value={variance>1?'near PC₁':'rotate toward long axis'} color={variance>1?GREEN:RED}/></MetricGrid></Artifact>;}

const OFFSET_POINTS=POINTS.map(p=>[p[0]+2.1,p[1]+1]);
function CenteringExplorer(){const[mode,setMode]=useState('centered'),cx=mode==='centered'?2.1:0,cy=mode==='centered'?1:0,angle=mode==='centered'?.55:.39,w=[Math.cos(angle),Math.sin(angle)];return <Artifact title="Interactive · Center before finding directions"><Choices choices={[["uncentered","From the origin"],["centered","Centered covariance"]]} value={mode} onChange={setMode}/><svg viewBox="0 0 640 270" role="img" aria-label="Effect of centering before PCA" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`}}><line x1="46" y1="225" x2="612" y2="225" stroke={GRID}/><line x1="146" y1="30" x2="146" y2="245" stroke={GRID}/><line x1={146+(cx-3*w[0])*85} y1={225-(cy-3*w[1])*58} x2={146+(cx+3*w[0])*85} y2={225-(cy+3*w[1])*58} stroke={mode==='centered'?BLUE:RED} strokeWidth="3"/>{OFFSET_POINTS.map((p,i)=><circle key={i} cx={146+p[0]*85} cy={225-p[1]*58} r="5" fill={PURPLE}/>) }<circle cx={146+2.1*85} cy={225-1*58} r="7" fill={ORANGE}/><text x={146+2.1*85+10} y={225-1*58-8} fontSize="11" fontFamily="monospace">mean</text></svg><p style={{color:'var(--muted)',fontSize:'.82rem',marginBottom:0}}>{mode==='centered'?'Subtracting the mean makes PCA describe variation around the cloud rather than its displacement from zero.':'Without centering, the first direction is pulled toward the mean and solves a different second-moment problem.'}</p></Artifact>;}

const EIGENVALUES=[9.2,4.8,2.3,1.1,.6,.25],TOTAL=EIGENVALUES.reduce((a,b)=>a+b,0);
function ReconstructionExplorer(){const[k,setK]=useState(2),kept=EIGENVALUES.slice(0,k).reduce((a,b)=>a+b,0),retained=kept/TOTAL;return <Artifact title="Interactive · Components trade detail for compression"><Control label="components K" value={k}><input aria-label="PCA reconstruction components" type="range" min="1" max={EIGENVALUES.length} value={k} onChange={e=>setK(Number(e.target.value))}/></Control><div style={{display:'grid',gridTemplateColumns:`repeat(${EIGENVALUES.length},1fr)`,gap:7,alignItems:'end',height:190,borderBottom:`1px solid ${GRID}`,marginTop:'1.2rem'}}>{EIGENVALUES.map((value,i)=><div key={i} style={{height:'100%',display:'grid',alignItems:'end',textAlign:'center'}}><div style={{height:`${value/10*145}px`,background:i<k?BLUE:'#d8dce4',position:'relative'}}><span style={{position:'absolute',top:-20,left:0,right:0,fontSize:'.62rem'}}>{value}</span></div><span style={{fontSize:'.64rem'}}>PC{i+1}</span></div>)}</div><MetricGrid><Metric label="variance retained" value={`${(retained*100).toFixed(1)}%`} color={GREEN}/><Metric label="discarded variance" value={(TOTAL-kept).toFixed(2)} color={ORANGE}/><Metric label="compression D → K" value={`${EIGENVALUES.length} → ${k}`} color={PURPLE}/></MetricGrid></Artifact>;}

function ScalingExplorer(){const[mode,setMode]=useState('raw');const angle=mode==='raw'?8:43,w=[Math.cos(angle*Math.PI/180),Math.sin(angle*Math.PI/180)];return <Artifact title="Interactive · Units can decide the first component"><Choices choices={[["raw","Raw units"],["standardized","Standardized features"]]} value={mode} onChange={setMode}/><svg viewBox="0 0 640 245" role="img" aria-label="PCA direction before and after feature standardization" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`}}><line x1="55" y1="205" x2="600" y2="205" stroke="#101318"/><line x1="55" y1="205" x2="55" y2="30" stroke="#101318"/><ellipse cx="325" cy="125" rx={mode==='raw'?210:155} ry={mode==='raw'?38:62} transform={`rotate(${-angle} 325 125)`} fill="#eef2ff" stroke={PURPLE}/><line x1={325-260*w[0]} y1={125+150*w[1]} x2={325+260*w[0]} y2={125-150*w[1]} stroke={BLUE} strokeWidth="3"/><text x="510" y="228" fontSize="11" fontFamily="monospace">feature 1</text><text x="18" y="40" fontSize="11" fontFamily="monospace">feature 2</text></svg><p style={{color:'var(--muted)',fontSize:'.82rem',marginBottom:0}}>{mode==='raw'?'A large numerical scale makes feature 1 dominate the covariance matrix and PC₁.':'Standardization gives both coordinates unit variance; correlation structure, not measurement units, determines the direction.'}</p></Artifact>;}

export default function PcaApp(){return <div style={{background:'var(--bg)',minHeight:'100vh'}}><Navbar/><header className="ns-header"><div className="container"><div style={{fontSize:'.82rem',color:'var(--muted)',marginBottom:'.35rem'}}><a href="/machinelearning/">Machine Learning</a> ›</div><div className="ns-title">Principal Component Analysis</div><div className="ns-subtitle">Rotate centered data toward its highest-variance directions, keep a compact set of orthogonal scores, and understand exactly what information reconstruction discards.</div><span className="tag">Dimensionality reduction · covariance eigenvectors · reconstruction</span></div></header><div className="container"><div className="ns-layout"><aside className="ns-sidebar"><PcaTableOfContents/></aside><main className="ns-content">
<section id="compression" className="ns-section"><h2>1. A Low-Dimensional Description</h2><p>A vector with <K l="D"/> measured features may lie close to a much smaller linear subspace. PCA represents it with <K l="K&lt;D"/> component scores and an orthonormal basis <K l="W"/>.</p><CompressionExplorer/><p>The columns of <K l="W\in\mathbb{R}^{D\times K}"/> are directions in the original feature space. The score vector <K l="z"/> is a new coordinate system, not a selected subset of original variables.</p></section>
<section id="axes" className="ns-section"><h2>2. PCA as a Change of Axes</h2><p>Ordinary coordinates measure a point along the original axes. PCA rotates those axes so the first follows the strongest variation, the second follows the strongest remaining perpendicular variation, and so on.</p><K block l="W^TW=I,\qquad z_n=W^T(x_n-\mu)"/><div className="formula-card"><strong>Sign does not matter:</strong> an eigenvector and its negative define the same axis. Scores change sign, but explained variance and reconstruction do not.</div></section>
<section id="variance" className="ns-section"><h2>3. Maximum Variance, Minimum Error</h2><p>For a unit direction <K l="w"/>, projected scores are <K l="z_n=w^T(x_n-\mu)"/> and their variance is <K l="w^TSw"/>. Rotate the axis below to see that spreading projections out is equivalent to shortening perpendicular reconstruction residuals.</p><ProjectionExplorer/><K block l="\max_{\lVert w\rVert=1}w^TSw\quad\Longleftrightarrow\quad\min_{\lVert w\rVert=1}\sum_n\lVert (x_n-\mu)-ww^T(x_n-\mu)\rVert^2"/></section>
<section id="eigen" className="ns-section"><h2>4. Covariance Eigenvectors</h2><p>With centered observations, the covariance matrix summarizes how features vary together:</p><K block l="S=\frac{1}{N}\sum_{n=1}^N(x_n-\mu)(x_n-\mu)^T"/><p>A Lagrange multiplier enforces unit length. Differentiating <K l="w^TSw-\lambda(w^Tw-1)"/> gives the eigenvalue equation:</p><K block l="Sw=\lambda w"/><p>The maximizing direction is the eigenvector with the largest eigenvalue. Its eigenvalue is exactly the variance of the data projected onto that component. Subsequent symmetric-matrix eigenvectors are orthogonal.</p><CenteringExplorer/></section>
<section id="algorithm" className="ns-section"><h2>5. The PCA Algorithm</h2><ol><li>Compute the training-set mean and center every observation.</li><li>Optionally standardize features when their scales should not carry meaning.</li><li>Compute the covariance matrix or apply singular value decomposition directly to the centered data matrix.</li><li>Order directions by descending eigenvalue or singular value.</li><li>Keep the first <K l="K"/> columns of <K l="W"/> and project with <K l="Z=X_cW"/>.</li><li>Use the same stored mean, scale, and basis for validation and new data.</li></ol><p>Fit preprocessing and PCA inside each training fold. Computing components on the full dataset before evaluation leaks information.</p></section>
<section id="reconstruction" className="ns-section"><h2>6. Reconstruction and Lost Information</h2><p>Projecting back produces the best rank-<K l="K"/> linear reconstruction in squared-error terms:</p><K block l="\hat{x}_n=WW^T(x_n-\mu)+\mu"/><ReconstructionExplorer/><p>Total centered variance equals the sum of all eigenvalues. Keeping the first <K l="K"/> components retains <K l="\sum_{j=1}^K\lambda_j"/> and the minimum average squared reconstruction error equals the sum of discarded eigenvalues.</p></section>
<section id="choose-k" className="ns-section"><h2>7. Choosing the Retained Dimension K</h2><K block l="\operatorname{retained}(K)=\frac{\sum_{j=1}^{K}\lambda_j}{\sum_{j=1}^{D}\lambda_j}"/><p>Choose the smallest <K l="K"/> that reaches a justified retained-variance threshold, lies near a scree-plot elbow, or performs well for the downstream task. A universal 95% rule does not exist: low-variance directions can still contain predictive or scientifically important signals.</p><ul><li>Inspect cumulative variance and reconstruction examples.</li><li>Validate <K l="K"/> jointly with the downstream model.</li><li>Check stability when eigenvalues are close; individual axes may rotate within an almost-tied subspace.</li></ul></section>
<section id="scaling" className="ns-section"><h2>8. Scaling and the SVD View</h2><ScalingExplorer/><p>Covariance PCA uses the original units. Correlation PCA—PCA after standardization—answers a different question and is often appropriate when feature units are incomparable.</p><K block l="X_c=U\Sigma V^T,\qquad W=V_{:,1:K},\qquad \lambda_j=\frac{\sigma_j^2}{N}"/><p>SVD avoids explicitly forming <K l="X_c^TX_c"/>, is numerically stable, and is especially useful when the feature dimension is large or the data matrix is sparse.</p></section>
<section id="uses" className="ns-section"><h2>9. What PCA Is Useful For</h2><table><thead><tr><th>Use</th><th>What PCA supplies</th></tr></thead><tbody><tr><td>Visualization</td><td>Two or three maximum-variance linear coordinates</td></tr><tr><td>Compression</td><td>Compact scores plus a reusable basis and mean</td></tr><tr><td>Denoising</td><td>Reconstruction after discarding low-variance directions</td></tr><tr><td>Collinearity</td><td>Orthogonal inputs for a downstream model</td></tr><tr><td>Images and faces</td><td>Basis images whose weighted sums approximate observations</td></tr></tbody></table><p>Component loadings show how original features contribute to each direction, while scores locate observations along it. Interpret both, and remember that sign is arbitrary.</p></section>
<section id="practice" className="ns-section"><h2>10. Assumptions and Limits</h2><ul><li>PCA is linear: curved manifolds may need kernel or nonlinear representation methods.</li><li>Squared error and covariance make it sensitive to outliers.</li><li>High variance is not automatically relevance, class separation, or causality.</li><li>Components mix original features and may be hard to name scientifically.</li><li>Mean imputation, scaling, and feature engineering all change the fitted axes.</li></ul><p>Always compare the reduced pipeline with an unreduced baseline. PCA can improve efficiency and conditioning, but it can also discard a subtle target signal or make explanations less direct.</p></section>
<section id="references" className="ns-section"><h2>References &amp; Resources</h2><p>Lecture notes: CS512 Machine Learning, Assoc. Prof. Öznur Taştan (Sabancı University)</p></section>
</main></div></div><footer className="footer"><div className="footer-bg" aria-hidden="true"/><div className="footer-inner"><div className="footer-left"><p className="footer-email">adleyba [at] sabanciuniv [dot] edu</p><p style={{margin:'.5rem 0 0',fontSize:'.78rem',opacity:.6,fontFamily:'var(--ff-mono)'}}>Machine Learning Study Guide · Built with React + KaTeX</p></div><p className="footer-copy">© 2026 — SIMA ADLEYBA</p></div></footer></div>;}
