import { useEffect, useRef, useState } from 'react';
import katex from 'katex';
import SvmTableOfContents from './components/SvmTableOfContents';
import './styles/global.css';

const BLUE = '#245cff', ORANGE = '#e67e22', GREEN = '#22995f', RED = '#d84a4a', PURPLE = '#7654d8', GRID = 'rgba(16, 19, 24, 0.14)';
function K({ l, block = false }) { const ref = useRef(null); useEffect(() => { if (ref.current) katex.render(l, ref.current, { throwOnError: false, displayMode: block }); }, [l, block]); return block ? <div ref={ref} style={{ overflowX: 'auto', margin: '0.8rem 0' }} /> : <span ref={ref} />; }
function Navbar() { const [menuOpen, setMenuOpen] = useState(false); return <nav className="ns-nav"><a className="nav-mark" href="/"><span className="dot" /></a><button className="ns-nav-burger" aria-label="Toggle menu" onClick={() => setMenuOpen(open => !open)}>☰</button><div className={`ns-nav-links${menuOpen ? ' mobile-open' : ''}`}>{['about','research','experience','education','studyguides','beyond'].map(item => <a key={item} href={`/#${item}`} onClick={() => setMenuOpen(false)}>{item === 'studyguides' ? 'study guides' : item}</a>)}<a href="/" target="_blank" rel="noopener">cv</a><span className="nav-pipe">|</span><a href="https://kimchikorelileriniskembesidir.com" className="field-notes" target="_blank" rel="noopener">personal blog</a></div></nav>; }
function Artifact({ title, children }) { return <div className="artifact-card"><h4>{title}</h4>{children}</div>; }
function Control({ label, value, children }) { return <label style={{ display:'grid', gap:'.35rem', minWidth:145, flex:1 }}><span style={{ display:'flex', justifyContent:'space-between', gap:'1rem', color:'var(--muted)', fontFamily:'var(--ff-mono)', fontSize:'.72rem' }}><span>{label}</span><strong style={{ color:BLUE }}>{value}</strong></span>{children}</label>; }
function Metric({ label, value, color=BLUE, note }) { return <div style={{ background:'#fff', padding:'.85rem 1rem', minWidth:0 }}><div style={{ color:'var(--muted)', fontFamily:'var(--ff-mono)', fontSize:'.66rem' }}>{label}</div><div style={{ color, fontSize:'1.2rem', fontWeight:700 }}>{value}</div>{note && <div style={{ color:'var(--muted)', fontSize:'.74rem' }}>{note}</div>}</div>; }
function MetricGrid({ children }) { return <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit, minmax(125px, 1fr))', gap:1, background:GRID, border:`1px solid ${GRID}`, marginTop:'1rem' }}>{children}</div>; }
function ChoiceButtons({ choices, value, onChange }) { return <div style={{ display:'flex', gap:'.5rem', flexWrap:'wrap', marginBottom:'1rem' }}>{choices.map(([id,label]) => <button key={id} type="button" aria-pressed={value===id} onClick={() => onChange(id)} style={{ padding:'.45rem .75rem', border:`1px solid ${value===id ? BLUE : GRID}`, background:value===id ? '#eef2ff' : '#fff', color:value===id ? BLUE : 'var(--muted)', cursor:'pointer' }}>{label}</button>)}</div>; }

const NEG = [[.7,1.1],[1.1,1.8],[1.5,.8],[1.7,2.1],[2.1,1.3]], POS = [[3.2,3.8],[3.7,3.1],[4.1,4.4],[4.6,3.5],[5,4.2]];
const sx = x => 44+x/5.7*566, sy = y => 225-y/5.2*190;
function MarginExplorer() {
  const [angle,setAngle] = useState(45), [offset,setOffset] = useState(360);
  const theta=angle*Math.PI/180, w=[Math.cos(theta),Math.sin(theta)], c=offset/100;
  const score=point => w[0]*point[0]+w[1]*point[1]-c;
  const labeled=[...NEG.map(p=>({p,y:-1})),...POS.map(p=>({p,y:1}))];
  const signed=labeled.map(item=>item.y*score(item.p)), correct=signed.filter(value=>value>0).length, margin=Math.max(0,Math.min(...signed));
  const support=labeled.map((item,index)=>({ ...item,index,d:Math.abs(score(item.p)) })).sort((a,b)=>a.d-b.d).slice(0,2);
  const lineY=x => (c-w[0]*x)/(Math.abs(w[1])<.05 ? .05:w[1]);
  return <Artifact title="Interactive · Search for a wide separating margin"><div style={{ display:'flex', gap:'1.3rem', flexWrap:'wrap' }}><Control label="normal angle" value={`${angle}°`}><input aria-label="SVM boundary angle" type="range" min="10" max="80" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></Control><Control label="boundary offset" value={c.toFixed(2)}><input aria-label="SVM boundary offset" type="range" min="180" max="520" value={offset} onChange={e=>setOffset(Number(e.target.value))}/></Control></div><svg viewBox="0 0 640 260" role="img" aria-label="SVM decision boundary and margin" style={{ width:'100%', background:'#f8f9fb', border:`1px solid ${GRID}`, marginTop:'1.2rem' }}>{[1,2,3,4,5].map(v=><g key={v}><line x1={sx(v)} y1="35" x2={sx(v)} y2="225" stroke={GRID}/><line x1="44" y1={sy(v)} x2="610" y2={sy(v)} stroke={GRID}/></g>)}{[-margin,margin].map((shift,index)=><line key={index} x1={sx(0)} y1={sy(lineY(0)+shift/Math.max(.05,w[1]))} x2={sx(5.7)} y2={sy(lineY(5.7)+shift/Math.max(.05,w[1]))} stroke={ORANGE} strokeDasharray="5 4"/>)}<line x1={sx(0)} y1={sy(lineY(0))} x2={sx(5.7)} y2={sy(lineY(5.7))} stroke={BLUE} strokeWidth="3"/>{NEG.map((p,i)=><rect key={`n${i}`} x={sx(p[0])-5} y={sy(p[1])-5} width="10" height="10" fill={RED} stroke={support.some(s=>s.y===-1&&s.index===i)?'#101318':'none'} strokeWidth="3"/>)}{POS.map((p,i)=><circle key={`p${i}`} cx={sx(p[0])} cy={sy(p[1])} r="6" fill={GREEN} stroke={support.some(s=>s.y===1&&s.index===NEG.length+i)?'#101318':'none'} strokeWidth="3"/>)}</svg><MetricGrid><Metric label="correctly separated" value={`${correct}/10`} color={correct===10?GREEN:RED}/><Metric label="minimum signed margin" value={margin.toFixed(2)} color={margin>.25?GREEN:ORANGE}/><Metric label="candidate support vectors" value="2" color={PURPLE} note="outlined nearest points"/></MetricGrid></Artifact>;
}

function SoftMarginExplorer() {
  const [cValue,setCValue]=useState(20), [outlier,setOutlier]=useState(40); const C=10**((cValue-20)/20), pressure=Math.log10(C+1), margin=2.4/(1+pressure), violation=Math.max(0,(outlier/10)-margin), objective=.5*(2/margin)**2+C*violation;
  return <Artifact title="Interactive · C trades margin for violations"><div style={{ display:'flex',gap:'1.3rem',flexWrap:'wrap' }}><Control label="penalty C" value={C.toFixed(2)}><input aria-label="SVM penalty C" type="range" min="0" max="60" value={cValue} onChange={e=>setCValue(Number(e.target.value))}/></Control><Control label="outlier intrusion" value={(outlier/10).toFixed(1)}><input aria-label="SVM outlier intrusion" type="range" min="0" max="60" value={outlier} onChange={e=>setOutlier(Number(e.target.value))}/></Control></div><div style={{ height:58,position:'relative',background:'#eef0f3',border:`1px solid ${GRID}`,marginTop:'1.3rem' }}><div style={{ position:'absolute',left:'50%',top:0,bottom:0,width:2,background:BLUE }}/><div style={{ position:'absolute',left:`${50-margin*9}%`,right:`${50-margin*9}%`,top:13,bottom:13,border:`2px dashed ${ORANGE}` }}/><div style={{ position:'absolute',left:`${Math.min(94,50+outlier/10*7)}%`,top:17,width:22,height:22,borderRadius:'50%',background:RED,transform:'translateX(-11px)' }}/></div><K block l="\min_{w,b,\xi}\frac{1}{2}\lVert w\rVert^2+C\sum_i\xi_i\quad\text{s.t.}\quad y_i(w^Tx_i+b)\ge1-\xi_i"/><MetricGrid><Metric label="conceptual margin width" value={margin.toFixed(2)} color={GREEN}/><Metric label="slack ξ" value={violation.toFixed(2)} color={violation?RED:GREEN}/><Metric label="objective" value={objective.toFixed(2)} color={PURPLE}/></MetricGrid></Artifact>;
}

function HingeExplorer() {
  const [margin,setMargin]=useState(20); const z=margin/10, hinge=Math.max(0,1-z), logistic=Math.log(1+Math.exp(-z));
  const path=Array.from({length:121},(_,i)=>{const x=-3+i/20,y=Math.max(0,1-x);return `${i?'L':'M'} ${44+i/120*566} ${220-Math.min(4,y)/4*178}`;}).join(' ');
  return <Artifact title="Interactive · Hinge loss ignores safe points"><Control label="signed margin z = yf(x)" value={z.toFixed(1)}><input aria-label="Signed SVM margin" type="range" min="-30" max="40" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></Control><svg viewBox="0 0 640 250" role="img" aria-label="Hinge loss as a function of signed margin" style={{ width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`,marginTop:'1.2rem' }}><line x1="44" y1="220" x2="610" y2="220" stroke="#101318"/><line x1={44+4/7*566} y1="40" x2={44+4/7*566} y2="220" stroke={ORANGE} strokeDasharray="4 4"/><path d={path} fill="none" stroke={BLUE} strokeWidth="3"/><circle cx={44+(z+3)/7*566} cy={220-Math.min(4,hinge)/4*178} r="7" fill={GREEN}/></svg><MetricGrid><Metric label="hinge loss" value={hinge.toFixed(3)} color={hinge?RED:GREEN}/><Metric label="logistic loss" value={logistic.toFixed(3)} color={ORANGE}/><Metric label="status" value={z>=1?'outside margin':z>=0?'inside margin':'misclassified'} color={z>=1?GREEN:z>=0?ORANGE:RED}/></MetricGrid></Artifact>;
}

function KernelMapExplorer() {
  const [view,setView]=useState('input'); const points=Array.from({length:24},(_,i)=>{const outer=i>=10,r=outer?2.15:0.85,a=(i%(outer?14:10))/(outer?14:10)*Math.PI*2;return {x:3+r*Math.cos(a),y:2.7+r*Math.sin(a),outer};});
  return <Artifact title="Interactive · A nonlinear map can reveal a linear split"><ChoiceButtons choices={[["input","Input space (x₁,x₂)"],["feature","Feature space r²"]]} value={view} onChange={setView}/><svg viewBox="0 0 640 250" role="img" aria-label="Concentric classes before and after feature transformation" style={{width:'100%',background:'#f8f9fb',border:`1px solid ${GRID}`}}>{view==='input'?<>{points.map((p,i)=>p.outer?<circle key={i} cx={sx(p.x)} cy={sy(p.y)} r="6" fill={GREEN}/>:<rect key={i} x={sx(p.x)-5} y={sy(p.y)-5} width="10" height="10" fill={RED}/>)}</>:<>{points.map((p,i)=>{const r2=(p.x-3)**2+(p.y-2.7)**2;return p.outer?<circle key={i} cx={90+r2/5.2*470} cy={110+(i%3-1)*12} r="6" fill={GREEN}/>:<rect key={i} x={90+r2/5.2*470-5} y={168+(i%3-1)*12-5} width="10" height="10" fill={RED}/>})}<line x1="245" y1="35" x2="245" y2="220" stroke={BLUE} strokeWidth="3"/></>}</svg><K block l="\phi(x_1,x_2)=x_1^2+x_2^2"/><p style={{color:'var(--muted)',fontSize:'.82rem',marginBottom:0}}>The kernel trick computes inner products <K l="\phi(x)^T\phi(z)"/> without constructing the mapped coordinates explicitly.</p></Artifact>;
}

function RbfExplorer() {
  const [distance,setDistance]=useState(15),[gammaValue,setGammaValue]=useState(10); const d=distance/10,gamma=gammaValue/10,similarity=Math.exp(-gamma*d*d);
  return <Artifact title="Interactive · RBF similarity locality"><div style={{display:'flex',gap:'1.3rem',flexWrap:'wrap'}}><Control label="distance ‖x−z‖" value={d.toFixed(1)}><input aria-label="RBF point distance" type="range" min="0" max="40" value={distance} onChange={e=>setDistance(Number(e.target.value))}/></Control><Control label="gamma γ" value={gamma.toFixed(1)}><input aria-label="RBF gamma" type="range" min="1" max="40" value={gammaValue} onChange={e=>setGammaValue(Number(e.target.value))}/></Control></div><K block l="k(x,z)=\exp(-\gamma\lVert x-z\rVert^2)"/><div style={{height:38,background:'#eef0f3',border:`1px solid ${GRID}`}}><div style={{height:'100%',width:`${similarity*100}%`,background:PURPLE,transition:'width .15s'}}/></div><MetricGrid><Metric label="kernel similarity" value={similarity.toFixed(4)} color={PURPLE}/><Metric label="effective radius" value={(1/Math.sqrt(gamma)).toFixed(2)} color={GREEN}/><Metric label="relationship" value={similarity>.5?'local neighbors':similarity>.05?'weakly related':'almost orthogonal'} color={similarity>.5?GREEN:ORANGE}/></MetricGrid></Artifact>;
}

export default function SvmApp() { return <div style={{background:'var(--bg)',minHeight:'100vh'}}><Navbar/><header className="ns-header"><div className="container"><div style={{fontSize:'.82rem',color:'var(--muted)',marginBottom:'.35rem'}}><a href="/machinelearning/">Machine Learning</a> ›</div><div className="ns-title">Support Vector Machines</div><div className="ns-subtitle">Choose the separating hyperplane with the widest safety margin, tolerate violations through hinge loss, and create nonlinear boundaries through kernels.</div><span className="tag">Maximum margin · support vectors · kernel methods</span></div></header><div className="container"><div className="ns-layout"><aside className="ns-sidebar"><SvmTableOfContents/></aside><main className="ns-content">
<section id="margin" className="ns-section"><h2>1. The Max-Margin Idea</h2><p>Linearly separable data admits infinitely many zero-training-error hyperplanes. SVM chooses the one with greatest clearance from the nearest observations, making small perturbations less likely to change a prediction.</p><MarginExplorer/></section>
<section id="geometry" className="ns-section"><h2>2. Hyperplane Geometry</h2><K block l="w^Tx+b=0,\qquad f(x)=\operatorname{sign}(w^Tx+b)"/><p>The vector <K l="w"/> is normal to the boundary. The signed geometric distance is <K l="(w^Tx+b)/\lVert w\rVert"/>. Scaling the parameters so the nearest points satisfy <K l="y_i(w^Tx_i+b)=1"/> gives a total margin of <K l="2/\lVert w\rVert"/>.</p><div className="formula-card"><strong>Support vectors</strong> are the closest or violating training observations. Moving non-support points slightly does not change the fitted hyperplane; moving a support vector can.</div></section>
<section id="hard-margin" className="ns-section"><h2>3. Hard-Margin SVM</h2><K block l="\min_{w,b}\frac12\lVert w\rVert^2\quad\text{s.t.}\quad y_i(w^Tx_i+b)\ge1\ \forall i"/><p>The convex objective maximizes margin while every constraint demands correct classification outside the margin band. One conflicting label or overlapping class can make the problem infeasible, so hard margin is mainly a geometric starting point.</p></section>
<section id="soft-margin" className="ns-section"><h2>4. Slack &amp; Soft Margins</h2><p>Slack <K l="\xi_i"/> records how far an example violates its margin constraint. Values between 0 and 1 remain correctly classified inside the margin; values above 1 cross the decision boundary.</p><SoftMarginExplorer/><p>Large <K l="C"/> prioritizes training violations and can create a narrow, sensitive margin. Small <K l="C"/> regularizes more strongly and tolerates errors for a wider boundary.</p></section>
<section id="hinge" className="ns-section"><h2>5. Hinge Loss</h2><K block l="\ell_{hinge}(y,f(x))=\max\{0,1-yf(x)\}"/><HingeExplorer/><p>Correct predictions still incur loss until their signed margin reaches one. Beyond that safety margin, hinge loss becomes exactly zero, unlike logistic loss, which continues shrinking smoothly.</p></section>
<section id="dual" className="ns-section"><h2>6. The Dual &amp; Sparse Support</h2><K block l="\max_{0\le\alpha_i\le C}\sum_i\alpha_i-\frac12\sum_{i,j}\alpha_i\alpha_jy_iy_jx_i^Tx_j,\qquad \sum_i\alpha_i y_i=0"/><K block l="w=\sum_i\alpha_i y_i x_i"/><p>KKT complementary slackness makes most <K l="\alpha_i"/> zero. Only support vectors contribute to the decision rule. The dual depends on inputs solely through pairwise dot products, opening the door to kernels, but its <K l="N\times N"/> Gram matrix can be expensive for very large datasets.</p></section>
<section id="kernels" className="ns-section"><h2>7. Nonlinear Boundaries &amp; the Kernel Trick</h2><p>A feature map can turn a nonlinear pattern in input space into a linearly separable pattern in feature space.</p><KernelMapExplorer/><table><thead><tr><th>Kernel</th><th>Definition</th><th>Shape</th></tr></thead><tbody><tr><td>Linear</td><td><K l="x^Tz"/></td><td>Original-space hyperplane</td></tr><tr><td>Polynomial</td><td><K l="(x^Tz+c)^d"/></td><td>Interactions through degree <K l="d"/></td></tr><tr><td>RBF / Gaussian</td><td><K l="e^{-\gamma\lVert x-z\rVert^2}"/></td><td>Localized nonlinear influence</td></tr></tbody></table></section>
<section id="rbf" className="ns-section"><h2>8. RBF Locality, C &amp; Gamma</h2><RbfExplorer/><p>High <K l="\gamma"/> makes each support vector influential only nearby, allowing intricate boundaries and overfitting. Low <K l="\gamma"/> produces a smoother global boundary. Tune <K l="C"/> and <K l="\gamma"/> jointly because one controls violation penalty while the other controls boundary flexibility.</p></section>
<section id="multiclass" className="ns-section"><h2>9. Multiclass SVM &amp; Practical Use</h2><p>Binary SVMs extend through one-vs-rest (<K l="K"/> classifiers) or one-vs-one (<K l="K(K-1)/2"/> classifiers). A direct multiclass hinge formulation learns one score vector per class:</p><K block l="\hat y=\arg\max_k w_k^Tx"/><ul><li>Standardize numerical features; distances, margins, <K l="C"/>, and <K l="\gamma"/> all depend on scale.</li><li>Encode categorical features before fitting and keep preprocessing inside cross-validation.</li><li>Use class-specific weights when error costs or class frequencies differ.</li><li>SVM scores are margins, not probabilities; probability calibration is a separate step.</li></ul></section>
<section id="tuning" className="ns-section"><h2>10. Tuning, Strengths &amp; Limits</h2><table><thead><tr><th>Symptom</th><th>Adjustment</th></tr></thead><tbody><tr><td>Underfit linear boundary</td><td>Try nonlinear features/kernel; raise <K l="C"/> cautiously</td></tr><tr><td>Wiggly RBF boundary</td><td>Lower <K l="\gamma"/> and/or <K l="C"/></td></tr><tr><td>Slow kernel training</td><td>Use linear/primal solver, approximation, or fewer examples</td></tr><tr><td>Unstable validation</td><td>Scale, stratify, and widen the hyperparameter search</td></tr></tbody></table><p>SVMs remain strong on medium-sized, high-dimensional datasets and teach margin-based regularization and kernels clearly. Kernel training scales poorly with sample size, tuning can be sensitive, and explanations are less direct than linear coefficients or shallow trees.</p></section>
<section id="references" className="ns-section"><h2>References &amp; Resources</h2><p>Lecture notes: CS512 Machine Learning, Assoc. Prof. Öznur Taştan (Sabancı University)</p><p style={{color:'var(--muted)',fontSize:'.88rem'}}>Lecture acknowledgements: Pirush Rai and Eric Xing.</p></section>
</main></div></div><footer className="footer"><div className="footer-bg" aria-hidden="true"/><div className="footer-inner"><div className="footer-left"><p className="footer-email">adleyba [at] sabanciuniv [dot] edu</p><p style={{margin:'.5rem 0 0',fontSize:'.78rem',opacity:.6,fontFamily:'var(--ff-mono)'}}>Machine Learning Study Guide · Built with React + KaTeX</p></div><p className="footer-copy">© 2026 — SIMA ADLEYBA</p></div></footer></div>; }
